services:
  user-service:
    container_name: user-service
    image: supanuttangsin/user-svc:latest
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - .env
